### ISSUE TITLE
It doenst work at all

### ISSUE THREAD

**Issue by anomaloussus** [smzm/hydrovim#3]
python is updated, dependencies are installed , tried a different terminal emulator to same issue.

**Comment by phalanx8** [comment]
same here lol.

**Comment by phalanx8** [comment]
Hey @anomaloussus,

i could fix it. Check out the pull request: https://github.com/smzm/hydrovim/pull/4. Or my fork (for the PR): https://github.com/phalanx8/hydrovim

**Comment by smzm** [comment]
> python is updated, dependencies are installed , tried a different terminal emulator to same issue.

Check prerequisites in your terminal : 
1. `awk` command should be available
2. `python` command should be available
3. Be sure `MunifTanjim/nui.nvim` plugin is installed.
4. Put `syntax on` in top of your neovim configuration file. (before hydrovim installation)

**Comment by phalanx8** [comment]
Hi @smzm,

i reverted everything and checked/tried those 4 points out, it doesn't work. Did u read my comments about `g:FileType`?
Echoing `g:FileType` shows me that it is empty womm, when i update the script it is set to vim. 
Also: By removing `silent` you will get the errors like `python not found` or `awk not found`.
